(require 'package)

(defvar marmalade '("marmalade" . "http://marmalade-repo.org/packages/"))
(defvar gnu '("gnu" . "http://elpa.gnu.org/packages/"))
(defvar melpa '("melpa" . "http://melpa.milkbox.net/packages/"))

;; Add marmalade to package repos
(add-to-list 'package-archives marmalade)
(add-to-list 'package-archives melpa t)

(package-initialize)

(unless (and (file-exists-p "~/.emacs.d/elpa/archives/marmalade")
             (file-exists-p "~/.emacs.d/elpa/archives/gnu")
             (file-exists-p "~/.emacs.d/elpa/archives/melpa"))
  (package-refresh-contents))

(defun packages-install (&rest packages)
  (mapc (lambda (package)
          (let ((name (car package))
                (repo (cdr package)))
            (when (not (package-installed-p name))
              (let ((package-archives (list repo)))
                (package-initialize)
                (package-install name)))))
        packages)
  (package-initialize)
  (delete-other-windows))

(packages-install
 (cons 'auto-indent-mode melpa)
 (cons 'autopair melpa)
 (cons 'clojure-mode melpa)
 (cons 'clojure-snippets melpa)
 (cons 'color-moccur melpa)
 (cons 'color-theme-sanityinc-tomorrow melpa)
 (cons 'dash melpa)
 (cons 'dired+ melpa)
 (cons 'dired-details melpa)
 (cons 'dired-details+ melpa)
 (cons 'duplicate-thing melpa)
 (cons 'eimp marmalade)
 (cons 'el-autoyas marmalade)
 (cons 'elisp-slime-nav melpa)
 (cons 'eproject melpa)
 (cons 'ess melpa)
 (cons 'expand-region melpa)
 (cons 'framesize marmalade)
 (cons 'fringe-helper melpa)
 (cons 'full-ack melpa)
 (cons 'gh melpa)
 (cons 'gist melpa)
 (cons 'git-blame melpa)
 (cons 'git-commit-mode melpa)
 (cons 'git-gutter melpa)
 (cons 'git-gutter-fringe melpa)
 (cons 'header2 melpa)
 (cons 'helm melpa)
 (cons 'helm-R melpa)
 (cons 'helm-ack melpa)
 (cons 'helm-ag melpa)
 (cons 'helm-c-moccur melpa)
 (cons 'helm-c-yasnippet melpa)
 (cons 'helm-cmd-t melpa)
 (cons 'helm-descbinds melpa)
 (cons 'helm-gist melpa)
 (cons 'helm-git melpa)
 (cons 'helm-gtags melpa)
 (cons 'helm-ls-git melpa)
 (cons 'helm-mercurial-queue melpa)
 (cons 'helm-migemo melpa)
 (cons 'helm-projectile melpa)
 (cons 'helm-themes melpa)
 (cons 'highline marmalade)
 (cons 'http-post-simple melpa)
 (cons 'key-chord melpa)
 (cons 'lib-requires melpa)
 (cons 'logito melpa)
 (cons 'magit melpa)
 (cons 'markdown-mode melpa)
 (cons 'markdown-mode+ melpa)
 (cons 'markup-faces melpa)
 (cons 'multi-term melpa)
 (cons 'multiple-cursors melpa)
 (cons 'org melpa)
 (cons 'org-email marmalade)
 (cons 'org-fstree melpa)
;; (cons 'org-jekyll melpa)
 (cons 'org-jira melpa)
 (cons 'org-mac-iCal melpa)
 (cons 'org-mac-link-grabber melpa)
;; (cons 'org-magit melpa)
 (cons 'org-mime marmalade)
 (cons 'org-outlook melpa)
;; (cons 'org-presie marmalade)
 (cons 'org-readme melpa)
 (cons 'org-table-comment marmalade)
 (cons 'org-toodledo melpa)
 (cons 'org2blog melpa)
 (cons 'paredit melpa)
 (cons 'pcache melpa)
 (cons 'projectile melpa)
 (cons 'r-autoyas marmalade)
 (cons 'rainbow-mode marmalade)
 (cons 's melpa)
 (cons 'scala-mode2 melpa)
 (cons 'smart-tab melpa)
 (cons 'xml-rpc melpa)
 (cons 'yaoddmuse melpa)
 (cons 'yas-jit marmalade)
 (cons 'yasnippet melpa))

(provide 'setup-package)
